name: data304-kdh
channels:
    - pyg
    - pytorch
    - nvidia
    - conda-forge

dependencies:
    - python=3.10
    
    - pytorch=2.3.1
    - torchvision
    - torchaudio
    - pytorch-cuda=12.1
    
    - pyg=2.6.1
    
    - numpy
    - pandas
    - tqdm
    
    - pip:
        - transformers